# Generated by Django 2.0.4 on 2018-04-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_system', '0002_singlerow_numberofpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerow',
            name='humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlerow',
            name='temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
