# Generated by Django 2.0.4 on 2018-04-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_system', '0003_auto_20180419_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
