# Generated by Django 2.0.4 on 2018-04-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_system', '0004_singleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
