# Generated by Django 2.0.4 on 2018-04-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_system', '0005_auto_20180420_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.DeleteModel(
            name='SingleImage',
        ),
    ]
